/**
 * @file czt_zoom_fft.h
 * @brief Chirp Z-transform spectrum refinement interfaces.
 */

#ifndef CZT_ZOOM_FFT_H
#define CZT_ZOOM_FFT_H

#include "arm_math.h"

/**
 * @brief Compute the refined CZT magnitude spectrum.
 * @param[in] input Input sample buffer; the current implementation reads 2048 samples.
 * @param[in] FS Sampling frequency in hertz.
 * @param[in] f_start Start frequency of the scan in hertz.
 * @param[in] f_end End frequency of the scan in hertz.
 * @param[out] zoom_abs Magnitude output buffer with space for 2048 values.
 */
void czt_Init_0(float32_t *input, int FS, int f_start, int f_end,
                float32_t *zoom_abs);

/**
 * @brief Return the frequency of the maximum CZT magnitude bin.
 * @param[in] FS Sampling frequency in hertz.
 * @param[in] f_start Start frequency of the scan in hertz.
 * @param[in] f_end End frequency of the scan in hertz.
 * @param[in] zoom_abs Magnitude spectrum generated by czt_Init_0().
 * @return Estimated frequency in hertz.
 */
float czt_result_fre(int FS, int f_start, int f_end, float32_t *zoom_abs);

/**
 * @brief Return the amplitude derived from the maximum CZT magnitude bin.
 * @param[in] FS Sampling frequency in hertz.
 * @param[in] f_start Start frequency of the scan in hertz.
 * @param[in] f_end End frequency of the scan in hertz.
 * @param[in] zoom_abs Magnitude spectrum generated by czt_Init_0().
 * @return Estimated signal amplitude.
 */
float czt_Amp(int FS, int f_start, int f_end, float32_t *zoom_abs);

/**
 * @brief Return the phase associated with the maximum CZT magnitude bin.
 * @param[in] FS Sampling frequency in hertz.
 * @param[in] f_start Start frequency of the scan in hertz.
 * @param[in] f_end End frequency of the scan in hertz.
 * @param[in] zoom_abs Magnitude spectrum generated by czt_Init_0().
 * @return Legacy phase estimate in radians.
 * @warning This legacy interface is retained for compatibility but is not part
 *          of the validated result set.
 */
float czt_Phase(int FS, int f_start, int f_end, float32_t *zoom_abs);

#endif /* CZT_ZOOM_FFT_H */
